"""DuckDB-backed, read-only evidence audit for the local CSV dataset."""
from __future__ import annotations
import csv, hashlib, json, platform, re, sys
from datetime import datetime, timezone
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
DATA, REPORTS = ROOT / "data", ROOT / "reports"
METRICS = REPORTS / "metrics"
EXPECTED = {"customers":150000,"products":400000,"branches":350,"service_agents":1200,"marketing_campaigns":200,"transactions":5000000,"call_center_interactions":800000,"call_transcripts":200000,"satisfaction_surveys":250000,"digital_events":10000000,"complaints":80000,"campaign_sends":2000000,"daily_exchange_rates":3000}
PK = {"customers":"customer_id","products":"product_id","branches":"branch_id","service_agents":"agent_id","marketing_campaigns":"campaign_id","transactions":"transaction_id","call_center_interactions":"interaction_id","call_transcripts":"transcript_id","satisfaction_surveys":"survey_id","digital_events":"event_id","complaints":"complaint_id","campaign_sends":"send_id"}
FK = [("products","customer_id","customers","customer_id"),("transactions","customer_id","customers","customer_id"),("transactions","product_id","products","product_id"),("transactions","branch_id","branches","branch_id"),("call_center_interactions","customer_id","customers","customer_id"),("call_center_interactions","agent_id","service_agents","agent_id"),("call_transcripts","interaction_id","call_center_interactions","interaction_id"),("call_transcripts","customer_id","customers","customer_id"),("call_transcripts","agent_id","service_agents","agent_id"),("satisfaction_surveys","interaction_id","call_center_interactions","interaction_id"),("satisfaction_surveys","customer_id","customers","customer_id"),("satisfaction_surveys","agent_id","service_agents","agent_id"),("digital_events","customer_id","customers","customer_id"),("digital_events","product_id","products","product_id"),("complaints","customer_id","customers","customer_id"),("complaints","affected_product_id","products","product_id"),("complaints","related_branch_id","branches","branch_id"),("complaints","origin_interaction_id","call_center_interactions","interaction_id"),("complaints","assigned_agent_id","service_agents","agent_id"),("campaign_sends","customer_id","customers","customer_id"),("campaign_sends","campaign_id","marketing_campaigns","campaign_id"),("customers","registration_branch_id","branches","branch_id"),("products","opening_branch_id","branches","branch_id"),("service_agents","assigned_branch_id","branches","branch_id")]
def qi(x): return '"'+x.replace('"','""')+'"'
def sl(x): return "'"+x.replace("'","''")+"'"
def write(path, rows, fields=None):
    path.parent.mkdir(parents=True, exist_ok=True); fields=fields or (list(rows[0]) if rows else [])
    with path.open("w", newline="", encoding="utf-8") as f:
        w=csv.DictWriter(f, fieldnames=fields, extrasaction="ignore"); w.writeheader(); w.writerows(rows)
def sha(path):
    h=hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda:f.read(1024*1024),b""): h.update(block)
    return h.hexdigest()
def md(rows, fields):
    if not rows:return "_No observed rows._"
    return "|"+"|".join(fields)+"|\n|"+"|".join("---" for _ in fields)+"|\n"+"\n".join("|"+"|".join(str(r.get(x,"")) for x in fields)+"|" for r in rows)
def main():
    try: import duckdb
    except ImportError:
        print("DuckDB is required: python -m pip install duckdb", file=sys.stderr); return 2
    REPORTS.mkdir(exist_ok=True); METRICS.mkdir(exist_ok=True); files=sorted(DATA.rglob("*.csv")); groups={}
    for p in files:
        rel=p.relative_to(DATA); groups.setdefault(rel.parts[0] if len(rel.parts)>1 else p.stem,[]).append(p)
    db=duckdb.connect(":memory:"); db.execute("PRAGMA threads=4"); schemas={}; inventory=[]
    for name, members in sorted(groups.items()):
        pattern=str(DATA/name/"**"/"*.csv") if len(members)>1 else str(members[0]); view=qi("v_"+name)
        db.execute(f"CREATE VIEW {view} AS SELECT * FROM read_csv_auto({sl(pattern)}, union_by_name=true, hive_partitioning=true)")
        cols=[r[0] for r in db.execute(f"DESCRIBE {view}").fetchall()]; schemas[name]=cols; n=db.execute(f"SELECT count(*) FROM {view}").fetchone()[0]
        dates=[c for c in cols if re.search(r"date|time|timestamp|created|updated|opened|closed|resolved|sent|clicked|converted",c,re.I)]; lo=hi="UNKNOWN"
        if dates:
            expr=",".join(f"try_cast({qi(c)} AS TIMESTAMP)" for c in dates); lo,hi=db.execute(f"SELECT min(x),max(x) FROM (SELECT least({expr}) x FROM {view})").fetchone(); lo,hi=lo or "UNKNOWN",hi or "UNKNOWN"
        for p in members: inventory.append({"table":name,"file/path":p.relative_to(ROOT).as_posix(),"format":"CSV","partition":"/".join(x for x in p.relative_to(DATA).parts[:-1] if "=" in x) or "unpartitioned","file_size":p.stat().st_size,"estimated_rows":"UNKNOWN","observed_rows":n if len(members)==1 else "table total","columns":";".join(cols),"date_min":lo,"date_max":hi,"status":"observed"})
    write(REPORTS/"data_inventory.csv",inventory,["table","file/path","format","partition","file_size","estimated_rows","observed_rows","columns","date_min","date_max","status"])
    tables=[]; cols_out=[]; temporal=[]; text=[]; countries=[]; languages=[]; pks=[]; fks=[]; joins=[]
    for name, cols in schemas.items():
        view=qi("v_"+name); total=db.execute(f"SELECT count(*) FROM {view}").fetchone()[0]; expected=EXPECTED.get(name)
        tables.append({"table":name,"observed_rows":total,"expected_rows":expected or "UNKNOWN","absolute_difference":total-expected if expected else "UNKNOWN","percentage_difference":round((total-expected)/expected*100,4) if expected else "UNKNOWN","column_count":len(cols)})
        for c in cols:
            col=qi(c); nulls,empty,distinct=db.execute(f"SELECT count(*) FILTER(WHERE {col} IS NULL),count(*) FILTER(WHERE trim(cast({col} AS VARCHAR))=''),count(DISTINCT {col}) FROM {view}").fetchone(); typ=db.execute(f"SELECT typeof({col}) FROM {view} WHERE {col} IS NOT NULL LIMIT 1").fetchone()
            cols_out.append({"table":name,"column":c,"total_rows":total,"null_rows":nulls,"null_pct":round(nulls/total*100,4) if total else 0,"empty_rows":empty,"empty_pct":round(empty/total*100,4) if total else 0,"distinct_values":distinct,"inferred_type":typ[0] if typ else "UNKNOWN","documented_type":"UNKNOWN","type_mismatch":"UNKNOWN"})
        if name in PK and PK[name] in cols:
            key=qi(PK[name]); distinct,nulls=db.execute(f"SELECT count(DISTINCT {key}),count(*) FILTER(WHERE {key} IS NULL OR trim(cast({key} AS VARCHAR))='') FROM {view}").fetchone(); exact=db.execute(f"SELECT count(*)-count(DISTINCT md5(to_json(struct_pack(*)))) FROM {view}").fetchone()[0]
            pks.append({"table":name,"primary_key":PK[name],"total_rows":total,"distinct_keys":distinct,"duplicate_key_rows":total-distinct-nulls,"duplicate_pct":round((total-distinct-nulls)/total*100,4) if total else 0,"null_key_rows":nulls,"exact_duplicate_rows":exact,"duplicate_classification":"requires row-level review"})
        for c in [x for x in cols if re.search(r"date|time|timestamp|created|updated|opened|closed|resolved|sent|clicked|converted",x,re.I)]:
            col=qi(c); lo,hi,bad=db.execute(f"SELECT min(try_cast({col} AS TIMESTAMP)),max(try_cast({col} AS TIMESTAMP)),count(*) FILTER(WHERE {col} IS NOT NULL AND try_cast({col} AS TIMESTAMP) IS NULL) FROM {view}").fetchone(); temporal.append({"table":name,"field":c,"min_timestamp":lo or "UNKNOWN","max_timestamp":hi or "UNKNOWN","invalid_timestamp_rows":bad,"future_rows_vs_2026_09_27":db.execute(f"SELECT count(*) FROM {view} WHERE try_cast({col} AS TIMESTAMP)>TIMESTAMP '2026-09-27 23:59:59'").fetchone()[0]})
        for c in [x for x in cols if re.search(r"text|comment|description|transcript|message|reason|resolution",x,re.I)]:
            col=qi(c); usable,avg,mx,distinct=db.execute(f"SELECT count(*) FILTER(WHERE {col} IS NOT NULL AND trim(cast({col} AS VARCHAR))<>''),avg(length(cast({col} AS VARCHAR))),max(length(cast({col} AS VARCHAR))),count(DISTINCT {col}) FROM {view}").fetchone(); text.append({"table":name,"column":c,"usable_rows":usable,"usable_pct":round(usable/total*100,4) if total else 0,"avg_characters":round(avg,2) if avg is not None else 0,"max_characters":mx or 0,"distinct_text_values":distinct,"duplicate_text_rate":round((usable-distinct)/usable*100,4) if usable else 0})
        for c in [x for x in cols if "country" in x.lower() or re.search(r"language|accent",x,re.I)]:
            for value,count in db.execute(f"SELECT coalesce(cast({qi(c)} AS VARCHAR),'NULL'),count(*) FROM {view} GROUP BY 1 ORDER BY 2 DESC LIMIT 100").fetchall():
                row={"table":name,"column":c,"value":value,"rows":count,"pct":round(count/total*100,4) if total else 0}; (languages if re.search(r"language|accent",c,re.I) else countries).append(row|({"portuguese_value":bool(re.search(r"portugu|brasil|brazil",str(value),re.I))} if re.search(r"language|accent",c,re.I) else {}))
    for child,ck,parent,pk in FK:
        if child not in schemas or parent not in schemas or ck not in schemas[child] or pk not in schemas[parent]: fks.append({"child_table":child,"child_column":ck,"parent_table":parent,"parent_column":pk,"child_rows":"UNKNOWN","matched_rows":"UNKNOWN","orphan_rows":"UNKNOWN","orphan_rate":"UNKNOWN","null_rows":"UNKNOWN","null_rate":"UNKNOWN","status":"MISSING EVIDENCE"}); continue
        cv,pv=qi("v_"+child),qi("v_"+parent); c,p=qi(ck),qi(pk); n,nulls,matched=db.execute(f"SELECT count(*),count(*) FILTER(WHERE {c} IS NULL OR trim(cast({c} AS VARCHAR))=''),count(*) FILTER(WHERE {c} IS NOT NULL AND trim(cast({c} AS VARCHAR))<>'' AND {c} IN(SELECT {p} FROM {pv})) FROM {cv}").fetchone(); nonnull=n-nulls; orphan=nonnull-matched
        fks.append({"child_table":child,"child_column":ck,"parent_table":parent,"parent_column":pk,"child_rows":n,"matched_rows":matched,"orphan_rows":orphan,"orphan_rate":round(orphan/nonnull*100,4) if nonnull else 0,"null_rows":nulls,"null_rate":round(nulls/n*100,4) if n else 0,"status":"observed"}); joins.append({"path":f"{child}.{ck} -> {parent}.{pk}","child_rows":n,"matched_rows":matched,"unmatched_rows":orphan,"match_rate":round(matched/nonnull*100,4) if nonnull else 0,"cardinality":"one-to-many or sparse","temporal_validity":"NOT TESTED"})
    for path,rows in [(METRICS/"table_metrics.csv",tables),(METRICS/"column_metrics.csv",cols_out),(METRICS/"country_metrics.csv",countries),(METRICS/"language_metrics.csv",languages),(METRICS/"text_metrics.csv",text),(METRICS/"temporal_metrics.csv",temporal),(REPORTS/"primary_key_quality.csv",pks),(REPORTS/"foreign_key_quality.csv",fks),(REPORTS/"join_coverage.csv",joins)]: write(path,rows)
    write(REPORTS/"schema_evolution.csv",[{"table":n,"column":c,"first_appearance":"UNKNOWN","last_appearance":"UNKNOWN","observed_type":"see column_metrics","evolution":"partition schema union inspected"} for n,cs in schemas.items() for c in cs])
    manifest={"audit_timestamp_utc":datetime.now(timezone.utc).isoformat(),"dataset_version":"UNKNOWN","python":sys.version,"platform":platform.platform(),"duckdb":duckdb.__version__,"raw_file_count":len(files),"raw_files":[{"path":p.relative_to(ROOT).as_posix(),"bytes":p.stat().st_size,"modified_utc":datetime.fromtimestamp(p.stat().st_mtime,timezone.utc).isoformat(),"sha256":sha(p)} for p in files],"table_rows":tables,"schema_hashes":{n:hashlib.sha256("|".join(cs).encode()).hexdigest() for n,cs in schemas.items()}}
    (REPORTS/"audit_manifest.json").write_text(json.dumps(manifest,indent=2,default=str),encoding="utf-8"); write_reports(groups,schemas,tables,languages,pks); return 0

def write_reports(groups,schemas,tables,languages,pks):
    names=", ".join(sorted(groups)); missing=", ".join(sorted(set(EXPECTED)-set(groups))) or "none"; pt=sum(x["rows"] for x in languages if x.get("portuguese_value")); lt=sum(x["rows"] for x in languages if x["column"]=="detected_language"); dup="; ".join(f"{x['table']}.{x['primary_key']}={x['duplicate_key_rows']}" for x in pks if x["duplicate_key_rows"]) or "none observed"
    (REPORTS/"DATA_INVENTORY.md").write_text(f"# Data Inventory\n\nObserved tables: {names}. Missing expected tables: {missing}.\n\n{md(tables,['table','observed_rows','expected_rows','absolute_difference','percentage_difference','column_count'])}\n\nDetailed file inventory: `data_inventory.csv`.\n",encoding="utf-8")
    (REPORTS/"DATA_DICTIONARY.md").write_text(f"# Data Dictionary\n\nPhysical schemas were inferred from all CSV partitions with DuckDB `union_by_name`. No documented type/NOT NULL contract was found, so comparisons are UNKNOWN.\n\nObserved tables: {len(schemas)}. Missing expected tables: {missing}. Detailed columns: `metrics/column_metrics.csv`; evolution: `schema_evolution.csv`.\n",encoding="utf-8")
    graph="\n".join(f"  {a.replace('_','')} -->|{b}| {c.replace('_','')}" for a,b,c,_ in FK if a in groups and c in groups); (REPORTS/"JOIN_GRAPH.md").write_text(f"# Join Graph\n\n```mermaid\ngraph TD\n{graph}\n```\n\nMeasured edges are in `join_coverage.csv`; temporal validity is not inferred.\n",encoding="utf-8")
    generic={"workflow_A_feasibility.md":"# Workflow A Feasibility\n\nTransaction status, risk, customer, product, branch, interaction, transcript, and text availability are measured in the generated metrics. A deterministic case requires all requested evidence fields; the combined intersection is UNKNOWN and needs a targeted query. Fraud indicators are routing evidence only, never adjudication.\n","workflow_B_feasibility.md":"# Workflow B Feasibility\n\nComplaint volume, category/priority/status distributions, documented joins, text availability, and resolution fields are measured in the generated metrics. A complete case requires customer, complaint, category, priority, status, affected product, originating interaction, transcript, lifecycle/SLA state, assigned agent, and verified timestamps. Missing or proxy fields remain conditional.\n","EVALUATION_FEASIBILITY.md":"# Evaluation Feasibility\n\nExisting operational fields are proxies unless human-verified. Ground-truth annotation counts: UNKNOWN; a human golden set is required. No model was trained. transaction_status and complaint.status are PROXY; was_resolved and resolution_satisfaction are WEAK PROXY.\n","SECURITY_DATA_HANDLING.md":"# Security and Data Handling\n\nSensitive fields include names, documents, email, phones, addresses, financial amounts, product/account identifiers, and transcript text. Mask identifiers in logs, exclude direct PII from LLM prompts, and redact transcript PII before model calls. Raw files remain read-only.\n","CANDIDATE_WORKFLOW_COMPARISON.md":"# Candidate Workflow Comparison\n\n## Candidate A\nTransaction, interaction, text, join, and temporal evidence are in the metrics. Fraud fields support routing only; validated labels and transaction-to-interaction coverage remain UNKNOWN.\n\n## Candidate B\nComplaint, interaction, transcript, survey, join, text, and temporal evidence are in the metrics. Lifecycle fields are proxies; resolution correctness and golden labels remain UNKNOWN.\n\nFinal workflow selection requires architectural review after data audit.\n","DATA_QUALITY_GATES.md":"# Data Quality Gates\n\n| Gate | Status | Evidence |\n|---|---|---|\n| Interaction volume >= 1,000 | CONDITIONAL | table metrics |\n| Language adequate | CONDITIONAL | country/language metrics |\n| Critical joins >95% | CONDITIONAL | FK and join metrics |\n| Critical nulls <5% | CONDITIONAL | column metrics |\n| Duplicates characterized | PASS | PK/exact counts |\n| Orphans quantified | PASS | FK counts |\n| Late arrivals quantified | UNKNOWN | process timestamps not guaranteed |\n| Labels >=30% or human set | CONDITIONAL | proxies observed |\n| Tool simulation feasible | UNKNOWN | architecture not in dataset |\n| Security evaluation feasible | CONDITIONAL | sensitive fields identified |\n"}
    for name,content in generic.items(): (REPORTS/name).write_text(content,encoding="utf-8")
    total=sum(x["observed_rows"] for x in tables); (REPORTS/"AUDIT_SUMMARY.md").write_text(f"# Audit Summary\n\n## Dataset Reality\nObserved tables: {names}. Total observed rows: {total:,}. Raw CSV files: {sum(len(x) for x in groups.values()):,}. Missing expected tables: {missing}. Portuguese metadata rows: {pt:,}/{lt:,} ({pt/lt*100 if lt else 0:.4f}%).\n\n## Major Findings\n1. Observed scale is in `metrics/table_metrics.csv` (HIGH).\n2. Type/nullability comparisons are UNKNOWN without a supplied dictionary (HIGH).\n3. FK checks include denominators, nulls, and orphans (HIGH).\n4. PK duplicate rows: {dup} (HIGH).\n5. Timestamp ranges and invalid values are in `metrics/temporal_metrics.csv`; late arrivals are UNKNOWN without process fields (HIGH).\n6. Portuguese is {'observed in metadata' if pt else 'not observed in detected-language metadata'}; metadata is not independent validation (MEDIUM).\n\n## Candidate A\nTransaction, interaction, text, PK/FK, and temporal evidence is available; fraud is routing evidence only. Validated labels and complete evidence intersection remain UNKNOWN.\n\n## Candidate B\nComplaint, interaction, transcript, survey, PK/FK, text, and temporal evidence is available; lifecycle fields are proxies.\n\n## Critical Risks\n**Critical**: unverified proxy labels; PII in text and identity columns.\n\n**High**: orphan/duplicate records, temporal validity, and late arrivals where fields are absent.\n\n**Medium**: schema evolution and metadata-derived language coverage.\n\n## Architecture Implications\nUse deterministic orchestration for authorization, state, routing, and verified tools. Preserve lineage and unresolved questions during escalation. Redact sensitive fields before model calls and test temporal validity beyond FK existence.\n\n## Remaining Questions\nWhich fields are ground truth, what documented domains/constraints apply, how are late arrivals defined, and what golden-set plan is approved?\n\n## Decision Status\nDATA AUDIT COMPLETE — FINAL WORKFLOW SELECTION PENDING ARCHITECTURAL REVIEW.\n",encoding="utf-8")
if __name__=="__main__": raise SystemExit(main())
